### ISSUE TITLE
TOKEN ?

### ISSUE THREAD

**Issue by qwertygc** [vekin03/Mail2RSS#1]
Bonjour !
À quoi correspond « TOKEN » ?
Merci

**Comment by vekin03** [comment]
Ce que j'appelle le "token" est en fait la clé d'accès, le mot de passe pour avoir accès au contenu du flux.

Supposons que le script soit à l'adresse ./mail2rss/index.php, cela évite à quelqu'un connaissant le chemin du script d'accéder au flux et, par conséquence, au contenu de votre boîte mail.

Ainsi, si le token est "t0ps3cr3t", il faudra entrer l'adresse  ./mail2rss/index.php?token=t0ps3cr3t pour être autorisé à voir le contenu du flux.

C'est une sécurité pour éviter que quiconque puisse lire vos mails...

**Comment by qwertygc** [comment]
OK. Merci :)
